@extends('layouts.app')
@php
use App\Support\FrenchDate; use App\Support\Money; use App\Support\Time;
$monthlyBalances=array_slice(array_filter($balance['by_month'],fn($i)=>($i['generated']??0)>0||($i['paid']??0)>0),-2,2,true);
@endphp
@section('content')
<div class="dashboard-page">
<section class="month-toolbar"><a class="square-control" href="{{ route('month.show',['month'=>$previousMonth]) }}">‹</a><div class="month-control"><i>▦</i><strong>{{ $monthLabel }}</strong></div><a class="square-control" href="{{ route('month.show',['month'=>$nextMonth]) }}">›</a></section>
<section class="kpis dashboard-kpis">
<article class="kpi kpi-hours"><div class="kpi-icon">◷</div><div><span>Heures ce mois</span><strong>{{ Time::formatDuration($report['worked_minutes']) }}</strong></div></article>
<article class="kpi kpi-overtime"><div class="kpi-icon">↗</div><div><span>Heures sup ce mois</span><strong>{{ Time::formatDuration($report['overtime_minutes']) }}</strong></div></article>
<article class="kpi kpi-money"><div class="kpi-icon">€</div><div><span>€ heures sup</span><strong>{{ Money::formatCents($report['overtime_cents']) }}</strong></div></article>
<article class="kpi kpi-meal"><div class="kpi-icon">◇</div><div><span>Paniers</span><strong>{{ Money::formatCents($report['meal_cents']) }}</strong></div></article>
<article class="kpi kpi-due"><div class="kpi-icon">▭</div><div><span>€ encore dus</span><strong>{{ Money::formatCents($balance['remaining']) }}</strong></div></article>
</section>
<div class="dashboard-grid">
<section class="panel days-panel" id="days"><div class="panel-heading days-heading"><div><h2>Jours du mois</h2><p>Seuls les jours appartenant au mois sélectionné sont affichés.</p></div><div class="save-state" id="save-state">Toutes les modifications sont enregistrées</div></div>
<div class="table-wrap month-table-wrap"><table class="work-table"><thead><tr><th>Date</th><th>Jour</th><th>Conduite</th><th>Entrepôt</th><th>Total</th><th>Repos</th><th>Fin</th><th>Panier</th><th>Note</th><th></th></tr></thead><tbody>
@foreach($calendarDays as $row) @php($day=$row['work_day'])
<tr class="work-row" data-date="{{ $row['date']->format('Y-m-d') }}" data-meal-mode="{{ $day?->meal_allowance_mode??'auto' }}" data-meal-amount="{{ $day?->meal_allowance_forced_cents!==null?number_format($day->meal_allowance_forced_cents/100,2,',',''):'' }}">
<td class="date-cell"><span class="desktop-date">{{ $row['date']->format('d/m/Y') }}</span><span class="mobile-date">{{ $row['date']->format('d/m') }}</span></td><td class="day-name {{ $row['date']->format('N')==7?'sunday':'' }}">{{ FrenchDate::day($row['date']) }}</td>
<td><input class="time-input autosave" name="driving" value="{{ $day?Time::formatDuration($day->driving_minutes):'' }}" placeholder="00:00"></td><td><input class="time-input autosave" name="warehouse" value="{{ $day?Time::formatDuration($day->warehouse_minutes):'' }}" placeholder="00:00"></td><td class="total-cell"><strong>{{ Time::formatDuration($row['worked']) }}</strong></td><td class="rest-cell"><span class="value-box">{{ Time::formatDuration($row['rest']) }}</span></td><td><input class="time-input autosave" name="end_time" value="{{ $day?Time::formatClock($day->end_time_minutes):'' }}" placeholder="—"></td><td class="meal-cell"><button type="button" class="meal-button edit-day">{{ Money::formatCents($row['meal']) }}⌄</button></td><td><input class="note-input autosave" name="note" value="{{ $day?->note??'' }}"></td><td><button class="more-button edit-day" type="button"><span class="desktop-more">⋮</span><span class="mobile-arrow">›</span></button></td>
</tr>@endforeach
</tbody></table></div><div class="days-footer"><button type="button" class="outline-button add-day-button" id="add-day">＋ Ajouter un jour</button><button type="button" class="mobile-more-days" id="toggle-days-mobile">Voir plus de jours⌄</button></div></section>
<aside class="right-column">
<section class="panel weeks-panel" id="weeks"><div class="panel-heading rail-heading"><div><h2>Semaines concernées</h2><p>Lundi → dimanche, limité au mois.</p></div><i>ⓘ</i></div><div class="week-list">@foreach($report['weeks'] as $week)<article class="week-card"><div><div class="week-title"><i>▦</i><strong>Semaine du {{ $week['start']->format('d/m') }} au {{ $week['end']->format('d/m') }}</strong></div><div class="week-metrics"><span>Total travaillé : <b class="blue-value">{{ Time::formatDuration($week['total_minutes']) }}</b></span><span>Heures sup : <b class="purple-value">{{ Time::formatDuration($week['overtime_minutes']) }}</b></span><span>Montant : <b class="green-value">{{ Money::formatCents($week['overtime_cents']) }}</b></span></div></div><i class="rail-arrow">›</i></article>@endforeach</div></section>
<section class="panel payments-rail"><div class="panel-heading rail-heading"><h2>Paiements heures sup</h2></div><div class="recent-payment-list">@forelse($recentPayments as $payment)<div class="recent-payment-row"><span class="payment-check">✓</span><span>{{ $payment->payment_date->format('d/m/Y') }}</span><strong>{{ Money::formatCents($payment->amount_cents) }}</strong><span>{{ $payment->period_reference?:($payment->note?:'heures sup') }}</span></div>@empty<div class="empty-payment">Aucun paiement enregistré.</div>@endforelse</div><a class="rail-add-button" href="{{ route('payments.index') }}">＋ Ajouter un paiement</a></section>
<section class="panel balance-panel" id="balance"><div class="panel-heading rail-heading"><h2>Reste dû</h2></div><div class="balance-card-body"><div class="balance-summary"><div><span>Global :</span><strong class="red-value">{{ Money::formatCents($balance['remaining']) }}</strong></div>@foreach($monthlyBalances as $m=>$i)<div><span>{{ FrenchDate::month((int)substr($m,5,2)) }} :</span><strong>{{ Money::formatCents($i['remaining']) }}</strong></div>@endforeach</div><div class="balance-watermark">▭</div></div>@if($balance['credit']>0)<div class="credit">Avance / trop-perçu : {{ Money::formatCents($balance['credit']) }}</div>@endif</section>
</aside></div>
<section class="panel below-fold-summary"><div class="panel-heading"><h2>Total théorique du mois</h2></div><div class="salary-summary-grid"><div><span>Heures normales</span><strong>{{ Money::formatCents($report['normal_pay_cents']) }}</strong></div><div><span>Heures sup</span><strong>{{ Money::formatCents($report['overtime_cents']) }}</strong></div><div><span>Travail total</span><strong>{{ Money::formatCents($report['work_pay_cents']) }}</strong></div><div><span>Paniers</span><strong>{{ Money::formatCents($report['meal_cents']) }}</strong></div><div class="salary-total"><span>Total</span><strong>{{ Money::formatCents($report['theoretical_total_cents']) }}</strong></div></div></section>
</div>
<dialog id="day-dialog" class="day-dialog"><form method="dialog" id="day-dialog-form"><div class="dialog-head"><h2>Édition du <span id="dialog-title">jour</span> <small id="dialog-day-name"></small></h2><button value="cancel" class="dialog-close">×</button></div><div class="dialog-grid"><label>Temps de conduite<input name="driving" placeholder="00:00"></label><label>Temps à l’entrepôt<input name="warehouse" placeholder="00:00"></label><label>Heure de fin<input name="end_time" placeholder="14:30"></label></div><fieldset class="meal-fieldset"><legend>Panier</legend><label><input type="radio" name="meal_mode" value="auto"> Automatique (16,00 €)</label><label><input type="radio" name="meal_mode" value="forced"> Forcer</label><input name="meal_amount" placeholder="0,00 €"></fieldset><label class="dialog-note-label">Note<textarea name="note" rows="2" placeholder="Ajouter une note..."></textarea></label><div class="dialog-actions"><button type="button" class="dialog-delete" id="delete-day">Supprimer</button><div><button value="cancel" class="dialog-cancel">Annuler</button><button type="button" class="dialog-save" id="save-day">Enregistrer</button></div></div><div class="inline-error" id="dialog-error"></div></form></dialog>
@endsection
