@extends('layouts.app')
@php
use App\Support\FrenchDate; use App\Support\Money; use App\Support\Time;
$monthlyBalances=array_slice(array_filter($balance['by_month'],fn($i)=>($i['generated']??0)>0||($i['paid']??0)>0),-2,2,true);
@endphp
@section('content')
<div class="dashboard-page">
<section class="month-toolbar"><a class="square-control" href="{{ route('month.show',['month'=>$previousMonth]) }}" aria-label="Mois précédent"><i class="fa-solid fa-chevron-left"></i></a><div class="month-control"><i class="fa-regular fa-calendar-days"></i><strong>{{ $monthLabel }}</strong></div><a class="square-control" href="{{ route('month.show',['month'=>$nextMonth]) }}" aria-label="Mois suivant"><i class="fa-solid fa-chevron-right"></i></a></section>
<section class="kpis dashboard-kpis">
<article class="kpi kpi-hours"><div class="kpi-icon"><i class="fa-regular fa-clock"></i></div><div><span>Heures ce mois</span><strong>{{ Time::formatDuration($report['worked_minutes']) }}</strong></div></article>
<article class="kpi kpi-overtime"><div class="kpi-icon"><i class="fa-solid fa-arrow-trend-up"></i></div><div><span>Heures sup ce mois</span><strong>{{ Time::formatDuration($report['overtime_minutes']) }}</strong></div></article>
<article class="kpi kpi-money"><div class="kpi-icon"><i class="fa-solid fa-euro-sign"></i></div><div><span>Heures sup</span><strong>{{ Money::formatCents($report['overtime_net_cents']) }} net</strong><small>{{ Money::formatCents($report['overtime_gross_cents']) }} brut</small></div></article>
<article class="kpi kpi-meal"><div class="kpi-icon"><i class="fa-solid fa-utensils"></i></div><div><span>Paniers</span><strong>{{ Money::formatCents($report['meal_cents']) }}</strong></div></article>
<article class="kpi kpi-due"><div class="kpi-icon"><i class="fa-solid fa-wallet"></i></div><div><span>€ encore dus</span><strong>{{ Money::formatCents($balance['remaining']) }}</strong></div></article>
</section>
<div class="dashboard-grid">
<section class="panel days-panel" id="days"><div class="panel-heading days-heading"><div><h2>Jours du mois</h2><p>Jaune : à remplir · Gris : repos.</p></div><div class="save-state" id="save-state">Toutes les modifications sont enregistrées</div></div>
<div class="table-wrap month-table-wrap"><table class="work-table"><thead><tr><th>Date</th><th>Jour</th><th>Début</th><th>Conduite</th><th>Entrepôt</th><th>Total</th><th>Repos</th><th>Fin</th><th>Panier</th><th></th></tr></thead><tbody>
@foreach($calendarDays as $row) @php($day=$row['work_day'])
<tr class="work-row {{ $row['is_rest']?'row-rest':($row['needs_fill']?'row-needs-fill':'row-filled') }}" data-date="{{ $row['date']->format('Y-m-d') }}" data-is-rest="{{ $row['is_rest']?'1':'0' }}" data-meal-mode="{{ $day?->meal_allowance_mode??'auto' }}" data-meal-amount="{{ $day?->meal_allowance_forced_cents!==null?Money::formatInput($day->meal_allowance_forced_cents):'' }}" data-meal-default="{{ $row['meal_default'] }}" data-meal-threshold="{{ $row['meal_threshold'] }}">
<td class="date-cell"><span class="desktop-date">{{ $row['date']->format('d/m/Y') }}</span><span class="mobile-date">{{ $row['date']->format('d/m') }}</span>@if($row['is_rest'])<small class="row-state-label">Repos</small>@elseif($row['needs_fill'])<small class="row-state-label">À remplir</small>@endif</td><td class="day-name {{ $row['date']->format('N')==7?'sunday':'' }}">{{ FrenchDate::day($row['date']) }}</td>
<td><input class="time-input autosave" name="start_time" value="{{ Time::formatClock($row['start']) }}" {{ $row['is_rest']?'disabled':'' }}></td><td><input class="time-input autosave" name="driving" value="{{ $day?Time::formatDuration($day->driving_minutes):'' }}" placeholder="00:00" {{ $row['is_rest']?'disabled':'' }}></td><td><input class="time-input autosave" name="warehouse" value="{{ $day?Time::formatDuration($day->warehouse_minutes):'' }}" placeholder="00:00" {{ $row['is_rest']?'disabled':'' }}></td><td class="total-cell"><strong>{{ $row['is_rest']?'—':Time::formatDuration($row['worked']) }}</strong></td><td class="rest-cell"><label class="rest-check" title="Jour de repos"><input type="checkbox" class="rest-toggle" {{ $row['is_rest']?'checked':'' }} aria-label="Jour de repos"><span>Repos</span></label></td><td class="end-cell"><span class="value-box end-value">{{ $row['is_rest']?'—':Time::formatClock($row['end']) }}</span></td><td class="meal-cell"><button type="button" class="meal-button edit-meal" {{ $row['is_rest']?'disabled':'' }}>@if($row['is_rest'])—@else{{ Money::formatCents($row['meal']) }} <i class="fa-solid fa-chevron-down"></i>@endif</button></td><td><button class="more-button edit-day" type="button" {{ $row['is_rest']?'disabled':'' }}><span class="desktop-more"><i class="fa-solid fa-ellipsis-vertical"></i></span><span class="mobile-arrow"><i class="fa-solid fa-chevron-right"></i></span></button></td>
</tr>@endforeach
</tbody></table></div><div class="days-footer"><button type="button" class="mobile-more-days" id="toggle-days-mobile">Voir plus de jours <i class="fa-solid fa-chevron-down"></i></button></div></section>
<aside class="right-column">
<section class="panel weeks-panel" id="weeks"><div class="panel-heading rail-heading"><div><h2>Semaines concernées</h2><p>Lundi → dimanche, limité au mois.</p></div><i class="fa-solid fa-circle-info"></i></div><div class="week-list">@foreach($report['weeks'] as $week)<article class="week-card"><div><div class="week-title"><i class="fa-regular fa-calendar-days"></i><strong>Semaine du {{ $week['start']->format('d/m') }} au {{ $week['end']->format('d/m') }}</strong></div><div class="week-metrics"><span>Total travaillé : <b class="blue-value">{{ Time::formatDuration($week['total_minutes']) }}</b></span><span>Heures sup : <b class="purple-value">{{ Time::formatDuration($week['overtime_minutes']) }}</b></span><span>Montant sup : <b class="green-value">{{ Money::formatCents($week['overtime_net_cents']) }} net</b></span></div></div></article>@endforeach</div></section>
<section class="panel balance-panel" id="balance"><div class="panel-heading rail-heading"><h2>Reste dû</h2></div><div class="balance-card-body"><div class="balance-summary"><div><span>Global net :</span><strong class="red-value">{{ Money::formatCents($balance['remaining']) }}</strong></div>@foreach($monthlyBalances as $m=>$i)<div><span>{{ FrenchDate::month((int)substr($m,5,2)) }} :</span><strong>{{ Money::formatCents($i['remaining']) }}</strong></div>@endforeach</div><div class="balance-watermark"><i class="fa-solid fa-wallet"></i></div></div>@if($balance['credit']>0)<div class="credit">Avance / trop-perçu : {{ Money::formatCents($balance['credit']) }}</div>@endif</section>
</aside></div>
<section class="panel below-fold-summary"><div class="panel-heading"><h2>Total théorique du mois</h2></div><div class="salary-summary-grid"><div><span>Heures normales</span><strong>{{ Money::formatCents($report['normal_net_cents']) }} net</strong><small>{{ Money::formatCents($report['normal_gross_cents']) }} brut</small></div><div><span>Paniers</span><strong>{{ Money::formatCents($report['meal_cents']) }}</strong></div><div class="salary-total"><span>Total hors heures sup</span><strong>{{ Money::formatCents($report['theoretical_net_cents']) }} net</strong><small>{{ Money::formatCents($report['theoretical_gross_cents']) }} brut</small></div><div class="salary-overtime"><span>Heures sup à part</span><strong>{{ Money::formatCents($report['overtime_net_cents']) }} net</strong><small>{{ Money::formatCents($report['overtime_gross_cents']) }} brut</small></div></div></section>
</div>
<dialog id="day-dialog" class="day-dialog"><form method="dialog" id="day-dialog-form"><div class="dialog-head"><h2><span id="dialog-heading-prefix">Édition du</span> <span id="dialog-title">jour</span> <small id="dialog-day-name"></small></h2><button value="cancel" class="dialog-close" aria-label="Fermer"><i class="fa-solid fa-xmark"></i></button></div><div class="dialog-grid"><label>Début<input name="start_time" placeholder="07:45"></label><label>Conduite<input name="driving" placeholder="00:00"></label><label>Entrepôt<input name="warehouse" placeholder="00:00"></label><label>Fin<span class="dialog-readonly" id="dialog-end">07:45</span></label></div><fieldset class="meal-fieldset"><legend>Panier</legend><label><input type="radio" name="meal_mode" value="auto"> Automatique <span id="dialog-auto-amount"></span></label><label><input type="radio" name="meal_mode" value="forced"> Forcer</label><input name="meal_amount" placeholder="0"></fieldset><div class="dialog-actions"><button type="button" class="dialog-delete" id="delete-day">Supprimer</button><div><button value="cancel" class="dialog-cancel">Annuler</button><button type="button" class="dialog-save" id="save-day">Enregistrer</button></div></div><div class="inline-error" id="dialog-error"></div></form></dialog>
@endsection
